PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?subjectLabel (COUNT(?case) AS ?n) WHERE {
  ?case a cdm:case-law ;
        cdm:resource_legal_is_about_subject-matter ?subject .
  ?subject skos:prefLabel ?subjectLabel .
  FILTER (LANG(?subjectLabel) = "en")
}
GROUP BY ?subjectLabel
ORDER BY DESC(?n)


prefix cdm: <http://publications.europa.eu/ontology/cdm#> 
select distinct ?ecli ?celex ?belonging_case_identifier ?domain ?title
where {
?w cdm:case-law_ecli ?ecli.
#FILTER(strstarts(str(?ecli), 'ECLI:EU:C:2021:137')).
?w cdm:resource_legal_id_celex ?celex.
?belonging_case cdm:dossier_contains_work ?w.
?belonging_case cdm:case_court_domain ?domain.
?belonging_case cdm:case_court_identifier_court ?court.

#?belonging_case cdm:case_court_identifier_number ?belonging_case_number.
?belonging_case cdm:dossier_identifier ?belonging_case_identifier.
#FILTER(CONTAINS(str(?belonging_case_identifier),"P")).

FILTER(str(?court)='C').
#FILTER(strstarts(str(?domain), 'LCC')).
?e cdm:expression_belongs_to_work ?w.
?e cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/ENG>.
?e cdm:expression_title ?title.
FILTER(strstarts(str(?title), 'Judgment')).
FILTER REGEX (str(?title), "(tax)").
}
ORDER BY DESC(?ecli)